Add means to write to different note/idea files depending on the situation

diff --git a/note b/note
--- a/note
+++ b/note
@@ -5,6 +5,12 @@
 
 mkdir -p notes
 CONTEXT_DESC=""
+if [[ -x ".getdesc" ]]; then
+    CONTEXT_DESC="_""`./.getdesc`"
+elif [[ -f ".getdesc" ]]; then
+    echo "Error: .getdesc exists but is not executable"
+    exit 1
+fi
 DATE_DESC="_$(date +%Y-%m-%d)"
 NOTEFILE="notes/note${CONTEXT_DESC}${DATE_DESC}.txt";
 
